-- PromptBridge007 Seed Data (tools only)
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('claude-code', 'claude-code', 'Claude Code', 'international', '"claude --version"', '["~/.claude/CLAUDE.md","./CLAUDE.md"]', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('cursor', 'cursor', 'Cursor', 'international', '"cursor --version"', '["./.cursor/rules/","./.cursorrules"]', '{"extension":".mdc","hasFrontmatter":true}', '{"targetDir":"./.cursor/rules/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('github-copilot', 'github-copilot', 'GitHub Copilot', 'international', '"gh copilot --version"', '"./.github/copilot-instructions.md"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.github/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('windsurf', 'windsurf', 'Windsurf', 'international', '"windsurf --version"', '["./.windsurfrules","./.windsurf/rules/"]', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('aider', 'aider', 'Aider', 'international', '"aider --version"', '["./.aider.conf.yml","./CONVENTIONS.md"]', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('gemini-cli', 'gemini-cli', 'Gemini CLI', 'international', '"gemini --version"', '"./GEMINI.md"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('codex', 'codex', 'Codex (OpenAI)', 'international', '"codex --version"', '["./CODEX.md","./codex.md"]', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('opencode', 'opencode', 'OpenCode', 'international', '"opencode --version"', '"./OPENCODE.md"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('openclaw', 'openclaw', 'OpenClaw', 'international', '"openclaw --version"', '"./.openclaw/agents/"', '{"extension":".md","hasFrontmatter":true}', '{"targetDir":"./.openclaw/agents/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('trae', 'trae', 'Trae', 'international', '"trae --version"', '"./.trae/rules/"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.trae/rules/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('amp', 'amp', 'Amp', 'international', '"amp --version"', '"./AMP.md"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('kiro', 'kiro', 'Kiro', 'international', '"kiro --version"', '"./.kiro/"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.kiro/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('replit', 'replit', 'Replit', 'international', '"replit --version"', '"./.replit/prompts/"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.replit/prompts/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('warp', 'warp', 'Warp', 'international', '"warp --version"', '"./.warp/prompts/"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.warp/prompts/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('kimi-code', 'kimi-code', 'Kimi Code', 'domestic', '"kimi-code --version"', '"./.kimi/"', '{"extension":".yaml","hasFrontmatter":false}', '{"targetDir":"./.kimi/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('coze', 'coze', 'æ£å­ Coze', 'domestic', '"coze --version"', '"./.coze/bots/"', '{"extension":".md","hasFrontmatter":true}', '{"targetDir":"./.coze/bots/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('glm', 'glm', 'æºè°± GLM', 'domestic', '"glm --version"', '"./.glm/"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.glm/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('doubao', 'doubao', 'è±å', 'domestic', '"doubao --version"', '"./.doubao/"', '{"extension":".yaml","hasFrontmatter":false}', '{"targetDir":"./.doubao/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('tongyi-lingma', 'tongyi-lingma', 'éä¹çµç ', 'domestic', '"tongyi-lingma --version"', '"./.tongyi/"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.tongyi/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('tiangong', 'tiangong', 'å¤©å·¥ AI', 'domestic', '"tiangong --version"', '"./.tiangong/"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.tiangong/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('qwen-code', 'qwen-code', 'Qwen Code', 'domestic', '"qwen-code --version"', '"./.qwen-code/"', '{"extension":".yaml","hasFrontmatter":false}', '{"targetDir":"./.qwen-code/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('deepseek-coder', 'deepseek-coder', 'DeepSeek Coder', 'domestic', '"deepseek-coder --version"', '"./.deepseek/"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.deepseek/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('spark-code', 'spark-code', 'æç«ä»£ç ', 'domestic', '"spark-code --version"', '"./.spark-code/"', '{"extension":".md","hasFrontmatter":false}', '{"targetDir":"./.spark-code/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO tools (id, name, display_name, category, detect_commands, prompt_paths, format_spec, deploy_config, is_active, created_at, updated_at) VALUES ('yuanbao', 'yuanbao', 'è¾è®¯åå®', 'domestic', '"yuanbao --version"', '"./.yuanbao/"', '{"extension":".json","hasFrontmatter":false}', '{"targetDir":"./.yuanbao/"}', 1, datetime('now'), datetime('now'));
INSERT OR IGNORE INTO projects (id, name, path, description, is_default, created_at, updated_at) VALUES ('default-project', 'Default Project', '/', 'Default project', 1, datetime('now'), datetime('now'));
